"use client";

import jsPDF from "jspdf";

interface TripPlan {
  itinerary: string;
  flights: string;
  hotels: string;
  budget: string;
  localTips: string;
}

interface TripPDFData {
  destination: string;
  startDate?: string;
  endDate?: string;
  budget?: number;
  travelers?: number;
  originCity?: string;
  plan: TripPlan;
}

const BRAND_BLUE: [number, number, number] = [15, 76, 129];
const TEAL: [number, number, number] = [46, 196, 182];
const ORANGE: [number, number, number] = [255, 107, 53];
const DARK_TEXT: [number, number, number] = [26, 26, 46];
const GRAY_TEXT: [number, number, number] = [100, 100, 110];
const GOLD: [number, number, number] = [255, 209, 102];

function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*/g, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^#+\s/gm, "");
}

export function generateTripPDF(data: TripPDFData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  function checkPageBreak(needed: number) {
    if (y + needed > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }
  }

  // Header banner
  doc.setFillColor(...BRAND_BLUE);
  doc.rect(0, 0, pageWidth, 50, "F");

  doc.setFillColor(...TEAL);
  doc.rect(0, 50, pageWidth, 3, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.text(`${data.destination} Trip Plan`, pageWidth / 2, 22, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...GOLD);
  const dateRange = data.startDate && data.endDate
    ? `${formatDate(data.startDate)} — ${formatDate(data.endDate)}`
    : "Dates TBD";
  doc.text(dateRange, pageWidth / 2, 32, { align: "center" });

  doc.setFontSize(9);
  doc.setTextColor(200, 220, 255);
  doc.text("Generated by Travelly — Your AI Travel Companion", pageWidth / 2, 42, { align: "center" });

  y = 60;

  // Summary chips
  const chips: string[] = [];
  if (data.budget) {
    chips.push(`Budget: ${new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(data.budget)}`);
  }
  if (data.travelers) chips.push(`Travelers: ${data.travelers}`);
  if (data.originCity) chips.push(`From: ${data.originCity}`);

  if (chips.length > 0) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const chipText = chips.join("  •  ");
    doc.setFillColor(240, 245, 250);
    doc.roundedRect(margin, y - 4, contentWidth, 12, 3, 3, "F");
    doc.setTextColor(...DARK_TEXT);
    doc.text(chipText, pageWidth / 2, y + 3, { align: "center" });
    y += 18;
  }

  const sections: { title: string; emoji: string; content: string }[] = [
    { title: "Itinerary", emoji: "📋", content: data.plan.itinerary },
    { title: "Flights", emoji: "✈️", content: data.plan.flights },
    { title: "Hotels", emoji: "🏨", content: data.plan.hotels },
    { title: "Budget Breakdown", emoji: "💰", content: data.plan.budget },
    { title: "Local Tips", emoji: "🎯", content: data.plan.localTips },
  ];

  for (const section of sections) {
    if (!section.content?.trim()) continue;

    checkPageBreak(20);

    // Section header
    doc.setFillColor(...TEAL);
    doc.rect(margin, y, contentWidth, 0.8, "F");
    y += 4;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...BRAND_BLUE);
    doc.text(`${section.title}`, margin, y + 4);
    y += 12;

    // Section content
    const cleaned = stripMarkdown(section.content);
    const lines = cleaned.split("\n");

    for (const line of lines) {
      if (line.trim() === "") {
        y += 3;
        continue;
      }

      const isDay = line.match(/^Day\s\d/i);
      const isBullet = line.startsWith("- ") || line.startsWith("• ");
      const isNumbered = line.match(/^\d+\./);
      const isPrice = line.includes("₹");

      if (isDay) {
        checkPageBreak(10);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(...ORANGE);
      } else if (isBullet || isNumbered) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(...GRAY_TEXT);
      } else if (isPrice) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(...TEAL);
      } else {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(...DARK_TEXT);
      }

      const textToRender = isBullet ? `  •  ${line.slice(2)}` : isNumbered ? `  ${line}` : line;
      const wrappedLines = doc.splitTextToSize(textToRender, contentWidth - 4);

      checkPageBreak(wrappedLines.length * 4.5);
      doc.text(wrappedLines, margin + 2, y);
      y += wrappedLines.length * 4.5;
    }

    y += 6;
  }

  // Footer on last page
  const footerY = pageHeight - 10;
  doc.setFillColor(245, 247, 250);
  doc.rect(0, footerY - 6, pageWidth, 16, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(150, 150, 160);
  doc.text("Generated by Travelly — travelly-pi.vercel.app", pageWidth / 2, footerY, { align: "center" });

  const fileName = `${data.destination.replace(/\s+/g, "-")}-trip-plan.pdf`;
  doc.save(fileName);
}

function formatDate(dateStr: string): string {
  return new Date(dateStr + "T00:00:00").toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}
